#ifndef _OfficeAutomation_Excel_h_
#define _OfficeAutomation_Excel_h_
#include "OfficeAutomation.h"

/* 
 Project created 01/18/2019 
 By Clément Hamon And Pierre Castrec
 Lib used to drive every Microsoft Application's had OLE Compatibility.
 This project have to be used with Ultimate++ FrameWork and required the Core Librairy from it
*/

class ExcelApp; //Class represents an   Excel Application 
class ExcelWorkbook; //Class represents Excel Workbook
class ExcelSheet; //Class represents an Excel WorkSheet
class ExcelRange; //Class represents an Excel Range
class ExcelCell; //Class represents  an Excel Cell

class ExcelApp : public Ole , public Upp::Moveable<ExcelApp> {
	private: 
		bool ExcelIsStarted; //Bool to know if we started Excel
		Upp::Vector<ExcelWorkbook> workbooks; //Vector of every workbook
	
	public:
		ExcelApp(); //Initialise COM
		~ExcelApp(); //Unitialise COM
		
		ExcelWorkbook* Workbooks(int index); //Allow to retrieve workbook by is index 
		ExcelWorkbook* Workbooks(Upp::String name); //Allow to retrieve workbook by is name
		
		bool Start(); //Start new Excel Application
		bool FindOrStart(); //Find running Excel or Start new One
		bool Quit(); //Close current Excel Application
		
		bool FindApplication(); //Find First current Excel Application still openned
		
		bool SetVisible(bool set); //Set or not the application visible 
		
		ExcelWorkbook* NewWorkbook(); //Create new Workbook and add it to actual excel Running method
		ExcelWorkbook* OpenWorkbook(Upp::String FilePath); //Find and Open Workbook by FilePath
		
		int GetNumberOfWorkbook(); //Return number of workbook currently openned on this excel App
	
};

class ExcelWorkbook : public Ole, public Upp::Moveable<ExcelWorkbook>{
	private:
		ExcelApp* parent; //Pointer to excelApp
		Upp::Vector<ExcelSheet> sheets; //Vector of every Worksheets
		bool isOpenned = false; //This bool must be useless But I prefere to have in case of object is still present in memory by a missing unreferenced pointer
	public:
		~ExcelWorkbook();
		ExcelWorkbook(ExcelWorkbook&&) = default; //Copy constructor
		ExcelWorkbook& operator=(ExcelWorkbook&&) = default; //moveable operator
		ExcelWorkbook(ExcelApp &parent,VARIANT AppObj); //Constructor basic
		
		ExcelSheet* Sheets(int index);//Allow to retrieve worksheet by is index 
		ExcelSheet* Sheets(Upp::String name);//Allow to retrieve worksheet by is name
		
		ExcelSheet* AddSheet(); //Create new Sheet with default Name
		ExcelSheet* AddSheet(Upp::String sheetName); //Create new Sheet with defined name 
		
		bool ResolveSheet(); //Function that calculate all the sheet on openned workbook
		bool isReadOnly(); //Return true if the workbook is readOnly
		
		bool Save(); //Save current workbook
		bool SaveAs(Upp::String filePath); //Save current workbook at filePath
		bool Close(); //Close current workbook
};

class ExcelSheet : public Ole, public Upp::Moveable<ExcelSheet>{
	private:
		ExcelWorkbook* parent;//Pointer to excelworkbook
	public:
		ExcelSheet(ExcelWorkbook &parent,VARIANT AppObj);
		~ExcelSheet();
		ExcelRange Range(Upp::String range); //Return a Range
		ExcelCell Cells(int ligne, int colonne); //Return a Cells
		
		bool SetName(Upp::String sheetName); //Redefine name of sheet
		int GetLastRow(Upp::String Colonne); //Retrieve last row of a colonne
		int GetLastColumn(); // Retrieve the last Column
		int GetRowNumberOfMySheet(); //Retrieve the max number generated by excel. It's usefull to make a huge range that wrap entire sheet
		ExcelRange GetCurrentRegion(); //Return ExcelRange that's represente the entire active range of the actual sheet
};

class ExcelRange : public Ole {
	private:
		ExcelSheet* parent; //Pointer to excelWorkbook
		Upp::String range;
	public:
		Upp::String GetTheRange();
		
		ExcelRange(ExcelSheet &parent,VARIANT appObj);
		ExcelRange(ExcelSheet &parent,VARIANT appObj,Upp::String actualRange);
		~ExcelRange();
		
		ExcelCell Cells(int ligne, int colonne); //Return a Cells
		/*
			Here we must add every method a Range could land  exemple : Borders
		*/
		
		Upp::Vector<ExcelCell> Value(); //Return every  Cells
		bool Value(Upp::String value); //set this value to every cells of the range
		bool Value(int value); //set this value to every cells of the range
};

class ExcelCell : public Ole , public Upp::Moveable<ExcelCell> {
	private:
		ExcelRange* parent= NULL; //pointer to the range 
	public: 
	
		ExcelCell(ExcelRange &parent,VARIANT appObj);
		ExcelCell(VARIANT appObj);
		~ExcelCell();
		/*
			Here we must add every method a cell could land 
		*/
		Upp::String Value();
		bool Value(Upp::String value);//Set value of Cells
		bool Value(int value);//Set value of Cells
		
};

#endif
